spring:
  application:
    name: pos
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/appdb}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  jooq:
    sql-dialect: POSTGRES
  grpc:
    server:
      health:
        enabled: false

grpc:
  server:
    port: 9090
